grav = 0.5;
hsp = 0;
vsp = 0;
stunned = 0
alarm[0] = 150
roaming = true
flying = false
straightthrow = false
stomped = false
thrown = false
reset = false
bombreset = 0
hp = 1
grounded = true

flash = false
birdcreated = false
boundbox = false
important = false
heavy = false
depth =0
grabbedby= 0
paletteselect = 1
stuntouchbuffer = 0
scaredbuffer = 0
movespeed  = global.baddiespeed
ragespr = spr_cheeseslime_rage
ragebuffer = 0
ragehitbox = false
img_angle = image_angle
offsetted = false
steppy = 20