grav = 0.5;
hsp = 0;
vsp = 0;
movespeed = 1
state = states.walk
stunned = 0
alarm[0] = 150
roaming = true
collectdrop = 5
flying = false
straightthrow = false
cigar = false
cigarcreate = false
stomped = false
shot = false
thrown = false
reset = false
bombreset = 0
hp = 5
grounded = true

idlespr = spr_robot_idle
stunfallspr = spr_robot_stun
walkspr =spr_robot_walk
stunspr = spr_robot_stun
grabbedspr = spr_robot_stun
image_xscale = -1
flash = false
slapped = false
birdcreated = false
boundbox = false
spr_dead = spr_robot_dead
important = false
heavy = false
depth =0